---
server:
  port: 8081

#spring:
#  datasource:
#    url: jdbc:h2:mem:atmdb
#    username: atmdb_admin
#    password: qwerty
#    driverClassName: org.h2.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
...