---
server:
  port: 8081
---
spring:
  datasource:
    url: jdbc:h2:mem:backdb
    username: h2admin
    password:
    driverClassName: org.h2.Driver

  jpa:
    # После автогенерации запускается инициализация на основе schema.sql/data.sql
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # (none) - отключает генерацию схемы/таблиц
      # (create-drop) - по умолчанию
      ddl-auto: create-drop

  h2:
    console:
      enabled: true
      # http://localhost:8081/h2db-console
      path: /h2db-console
...